import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import { AnimeProvider } from "./(categorias)/animes/componentes/contexto";
import { FilmesProvider } from "./(categorias)/filmes/componentes/contexto";
import { SeriesProvider } from "./(categorias)/series/componentes/contexto";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`mt-[75px] bg-black`}>
        <AnimeProvider>
          <FilmesProvider>
            <SeriesProvider>
              <Header />
              {children}
            </SeriesProvider>
          </FilmesProvider>
        </AnimeProvider>
      </body>
    </html>
  );
}
